Notifications and accounts deleting features
AlexanderKiselyov/feed-migrator pull request #40
Opened 2023-04-20 22:00 UTC by Anilochka

2023-04-22 10:23 UTC, a-yasevich requested changes

2023-04-22 10:23 UTC, a-yasevich commented on tg-bot/src/main/java/polis/data/repositories/ChannelGroupsRepository.java
> +    public void deleteAllChannelGroups(long channelId, String socialMedia) throws DataAccessException {
По-моему, название метода не соответствует тому, что он делает🙂 Такой запрос удалит у канала все группы с заданной социальной сетью (а по факту одну группу, так так мы договорились, что в канале одна группа для одной социальной сети

2023-04-22 10:23 UTC, a-yasevich commented on tg-bot/src/main/java/polis/bot/Bot.java
> +                channelGroupsRepository.deleteAllChannelGroups(currentChannel.getChannelId(),
Если правильно помню, то мы позволяем юзеру иметь в разных каналах разные группы, но для одного акканта. А мы здесь удаляем аккаунт только в пределах одного канала.

2023-04-22 10:26 UTC, a-yasevich commented
Чекнул удаление аккаунта. Нотификикации пока не смотрел,  пошёл свои таски делать.  Можно Сашу попросить  ещё глянуть😄

2023-04-25 17:29 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/commands/AddOkAccount.java
> +import polis.util.State;
лишний импорт

2023-04-25 17:29 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/commands/Notifications.java
> +                        currentGroup.getSocialMedia()));
в этом случае notificationsEnable == "" и следующий sendAnswer ничего не выведет

2023-04-29 12:52 UTC, a-yasevich approved these changes

2023-04-29 12:52 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/AccountsList.java
> +            buttons[tmpIndex + 2] = "\uD83D\uDDD1 Удалить";
\uD83D\uDDD1 стоит вынести в константу, по названию которой можно будет понять, что это за смайлик

2023-04-29 12:52 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/AccountsList.java
>      private String[] getAccountsArray(List<Account> socialMediaAccounts) {
Я бы назвал getButtonsForAccounts или типа того. Метод же возвращает кнопки (точнее их текст), а не массив аккаунтов)

2023-04-29 12:52 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/AccountsList.java
>                      dataCheck.getOKUsername(socialMediaAccounts.get(i).getAccessToken()),
Я бы вынес имя аккаунта в отдельную переменную. Да и сам Account тоже можно)

2023-04-30 10:08 UTC, merged