VK Authorization
AlexanderKiselyov/feed-migrator pull request #47
Opened 2023-04-27 22:16 UTC by AlexanderKiselyov

2023-04-28 08:00 UTC, Anilochka reviewed
написала по мелочам :)

2023-04-28 08:00 UTC, Anilochka commented on tg-bot/src/main/java/polis/commands/AddGroup.java
>      private static final int rowsCount = 2;
тут наверное лучше исправить на количество рядов 3, чтобы было лучше видно кнопки

2023-04-28 08:00 UTC, Anilochka commented on tg-bot/src/main/java/polis/commands/VkAccountDescription.java
> +    private static final int rowsCount = 2;
а тут 1, рядов должно быть <=, чем количество кнопок

2023-04-28 08:00 UTC, Anilochka commented on tg-bot/src/main/java/polis/util/State.java
> +            Map.entry(VkAccountDescription, AddGroup)
и предыдущий стейт для AddVkGroup надо

2023-05-03 11:21 UTC, a-yasevich requested changes

2023-05-03 11:21 UTC, a-yasevich commented on tg-bot/build.gradle.kts
> +    runtimeOnly("com.vk.api:sdk:1.0.9")
Убрать это

2023-05-03 11:21 UTC, a-yasevich commented on vk-api/build.gradle.kts
> +    compileOnly("com.vk.api:sdk:1.0.9")
Заменить на implementaion

2023-05-03 12:00 UTC, closed without merging