VK Integration
AlexanderKiselyov/feed-migrator pull request #59
Opened 2023-05-03 18:12 UTC by AlexanderKiselyov

2023-05-03 20:58 UTC, a-yasevich approved these changes

2023-05-03 20:58 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/NonCommand.java
> +        } else if (state.equals(Substate.AddVkAccount_AuthCode)) {
Тут пипец некрасиво это if else смотрится, мб свитч лучше будет

2023-05-03 20:59 UTC, a-yasevich commented
В целом в будущем нужно будет поизбавляться от сетевых запросов при формировании списков аккаунтов/групп

2023-05-03 21:04 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/AddVkAccount.java
> +                    rowsCount,
rowsСounts константой сделать в родительском классе

2023-05-03 21:04 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/VkAccountDescription.java
> +    private static final int rowsCount = 1;
Константы же капсом именуются

2023-05-03 21:31 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/commands/AddVkAccount.java
> +                    rowsCount,
поправил

2023-05-03 21:32 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/commands/VkAccountDescription.java
> +    private static final int rowsCount = 1;
поправил

2023-05-03 21:33 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/commands/NonCommand.java
> +        } else if (state.equals(Substate.AddVkAccount_AuthCode)) {
state является переменной интерфейса IState, поэтому в switch ее добавлять нельзя
в этой переменной могут быть как экземпляры State. так и экземпляры Substate

2023-05-05 14:20 UTC, a-yasevich requested changes

2023-05-05 14:20 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/TgSyncGroups.java
>                      switch (group.getSocialMedia()) {
Убрать этот свич и брать названия групп из базы. В сеть каждый раз ходить не круто, и запрос в вк у меня сегодня фейлился))

2023-05-05 14:24 UTC, a-yasevich requested changes

2023-05-05 14:24 UTC, a-yasevich commented on tg-bot/src/main/java/polis/bot/Bot.java
> +                Account account = accountsRepository.getUserAccount(userChatId, group.getAccountId(),
Да и аккаунт  получать не нужно, всё есть в ChannelGroup))

2023-05-05 14:38 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/commands/TgSyncGroups.java
>                      switch (group.getSocialMedia()) {
исправил

2023-05-05 14:38 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/bot/Bot.java
> +                Account account = accountsRepository.getUserAccount(userChatId, group.getAccountId(),
исправил

2023-05-08 09:39 UTC, a-yasevich approved these changes

2023-05-08 09:39 UTC, a-yasevich commented on tg-bot/src/main/java/polis/bot/Bot.java
> +                    CurrentAccount currentAccount = currentAccountRepository.getCurrentAccount(chatId);
Соцсеть по идее можно вытащить из колбека. Будет оптимальнее

2023-05-08 09:39 UTC, a-yasevich commented on tg-bot/src/main/java/polis/bot/Bot.java
> +                String currentAccountSocialMedia = currentAccountRepository.getCurrentAccount(chatId).getSocialMedia();
И тут.

2023-05-08 09:51 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/bot/Bot.java
> +                    CurrentAccount currentAccount = currentAccountRepository.getCurrentAccount(chatId);
в колбэке передается только id группы и параметр 0 или 1 - выбрать группу или удалить соответственно

2023-05-08 09:54 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/bot/Bot.java
> +                String currentAccountSocialMedia = currentAccountRepository.getCurrentAccount(chatId).getSocialMedia();
в колбэке передается только id аккаунта и параметр 0 или 1 - выбрать аккаунт или удалить соответственно (см. класс AccountsList)

2023-05-08 10:45 UTC, merged