Improved groups and accounts callback, added buttons
AlexanderKiselyov/feed-migrator pull request #61
Opened 2023-05-04 16:22 UTC by Anilochka

2023-05-04 18:29 UTC, a-yasevich approved these changes

2023-05-04 18:29 UTC, a-yasevich commented on tg-bot/src/main/java/polis/bot/Bot.java
>                  if (Objects.equals(dataParts[2], "0")) {
Мне ток не нравится, что немного неочевидно для читателя, что 0 по индексу 2 это простой клик по группе, а 1 это удаление. Если согласна, то можно вынести эти проверки в читабельные статические методы типа isJustClick() и isDeleteRequested() - ctrl alt m шорткат в идее.

2023-05-04 18:29 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/AccountsList.java
>              SocialMedia tmpAccountSocialMedia = tmpAccount.getSocialMedia();
Можно, раз уж ты этот файл потрогала, tmpIndex заменить на просто j, а у переменных с припиской tmp поубирать её. Типа просто аккаунт, просто socialMedia, зачем тут tmp)))

2023-05-04 18:29 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/AccountsList.java
> +                // TODO здесь бы сделать continue и уменьшить размер массива кнопок и accounts.size() (который
Не понял этот TODO. accountUsername = null, когда соцсеть неправильная, чего по идее быть не должно и это исключительная ситуация. Я б в default кейсе логгировал и кидал IllegalState какой-нить, или IllegalArgument

2023-05-04 18:33 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/AccountsList.java
> +                // TODO здесь бы сделать continue и уменьшить размер массива кнопок и accounts.size() (который
Тогда кстати можно будет сразу приравнять String accountUsername = switch (accountSocialMedia) {...

2023-05-04 18:44 UTC, Anilochka commented on tg-bot/src/main/java/polis/commands/AccountsList.java
> +                // TODO здесь бы сделать continue и уменьшить размер массива кнопок и accounts.size() (который
> Тогда кстати можно будет сразу приравнять String accountUsername = switch (accountSocialMedia) {...

еще accountUsername = null, если возникла ошибка при получении имени пользователя, и, как мне кажется, не очень будет выводить кнопку, где вместо имени пользователя null
я это имела ввиду в туду) так-то это странная ситуация, если аккаунт есть в БД, но по какой-то причине мы не смогли получить по запросу к ОК/ВК имя пользователя

2023-05-04 18:55 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/AccountsList.java
> +                // TODO здесь бы сделать continue и уменьшить размер массива кнопок и accounts.size() (который
Да, точно. null нельзя выводить в любом случае, в свитче я бы исключение кидал, а тут нужно наверное просто написать юзеру сообщение об ошибке и выйти. По поводу сетевых запросов, в будущем будет круто от них избавиться))

2023-05-04 18:58 UTC, Anilochka commented on tg-bot/src/main/java/polis/commands/AccountsList.java
> +                // TODO здесь бы сделать continue и уменьшить размер массива кнопок и accounts.size() (который
> Да, точно. null нельзя выводить в любом случае, в свитче я бы исключение кидал, а тут нужно наверное просто написать юзеру сообщение об ошибке и выйти. По поводу сетевых запросов, в будущем будет круто от них избавиться))

оки) про сетевые запросы согласна)

2023-05-05 12:02 UTC, a-yasevich requested changes

2023-05-05 12:02 UTC, a-yasevich commented on tg-bot/src/main/java/polis/bot/Bot.java
> +                    String socialMediaName = dataParts[2];
Тут индекс неправильный
<img width="849" alt="Снимок экрана 2023-05-05 в 13 57 46" src="https://user-images.githubusercontent.com/70908206/236452014-60700608-4441-43d3-820d-f02716dfc5d9.png">

2023-05-08 09:42 UTC, a-yasevich approved these changes

2023-05-08 10:36 UTC, merged