Channel title fix
AlexanderKiselyov/feed-migrator pull request #82
Opened 2023-05-21 19:56 UTC by AlexanderKiselyov

Channel title fix + same channel add fix

2023-05-21 21:03 UTC, a-yasevich requested changes
Спасиб, что решил поправить)

2023-05-21 21:03 UTC, a-yasevich commented on tg-bot/src/main/java/polis/commands/NonCommand.java
> +                JSONObject chatParameters = telegramDataCheck.getChatParameters(checkChannelLink);
Надо бы инкапсулировать процесс излечения названия токена, т.е. чтобы метод возвращал String. И назвать бы метод типа getChatName))

2023-05-21 21:28 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/commands/NonCommand.java
> +                JSONObject chatParameters = telegramDataCheck.getChatParameters(checkChannelLink);
хочется 1 раз сходить в апи Телеграмма и получить все нужные поля, а я получаю здесь 2 поля: id и title. Если я сделаю 2 метода (getChatId и getChatTitle), то у меня будет 2 вызова к апи для получения 2 полей одного чата

2023-05-21 22:12 UTC, AlexanderKiselyov commented on tg-bot/src/main/java/polis/commands/NonCommand.java
> +                JSONObject chatParameters = telegramDataCheck.getChatParameters(checkChannelLink);
добавил инкапсуляцию JSON объекта

2023-05-22 18:17 UTC, a-yasevich approved these changes

2023-05-24 19:37 UTC, Anilochka approved these changes

2023-05-26 17:01 UTC, merged